# Generated by Django 4.1.5 on 2023-01-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='passport', to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(related_name='subject', to='accounts.student'),
        ),
    ]
